# Copyright 2026 Canonical Ltd.

"""Component to manage the required relations to Istio when in ambient mode."""

from logging import getLogger

from charmed_kubeflow_chisme.components import Component
from charmed_kubeflow_chisme.exceptions import GenericCharmRuntimeError
from charms.istio_beacon_k8s.v0.service_mesh import ServiceMeshConsumer
from charms.istio_ingress_k8s.v0.istio_ingress_route import (
    BackendRef,
    HTTPPathMatch,
    HTTPRoute,
    HTTPRouteMatch,
    IstioIngressRouteConfig,
    IstioIngressRouteRequirer,
    Listener,
    PathModifier,
    PathModifierType,
    ProtocolType,
    URLRewriteFilter,
    URLRewriteSpec,
)
from ops import ActiveStatus

logger = getLogger(__name__)


class AmbientIngressRequirerComponent(Component):
    """Component to manage the required relations to Istio when in ambient mode."""

    def __init__(
        self,
        *args,
        path_matched_prefix: str,
        path_rewritten_prefix: str,
        relation_name: str,
        service_name: str,
        service_port: int,
        **kwargs,
    ):
        super().__init__(*args, **kwargs)

        self.path_matched_prefix = path_matched_prefix
        self.path_rewritten_prefix = path_rewritten_prefix
        self.relation_name = relation_name
        self.service_name = service_name
        self.service_port = service_port

        self._mesh = ServiceMeshConsumer(
            self._charm,
            policies=None,  # NOTE: no AuthorizationPolicies necessary because... why? TODO
        )
        self.ingress = IstioIngressRouteRequirer(self._charm, relation_name=self.relation_name)
        self._events_to_observe = [self.ingress.on.ready]

    def _get_ingress_config(self):
        http_listener = Listener(
            port=80,  # expecting ingress traffic to come through the default HTTP port: 80
            protocol=ProtocolType.HTTP  # expecting ingress traffic via HTTP
            # NOTE: listener name auto-generated by the charm
        )

        return IstioIngressRouteConfig(
            model=self._charm.model.name,  # NOTE: requirer's namespace, where target services live
            listeners=[http_listener],
            http_routes=[
                # resource of kind `HTTPRoute.gateway.networking.k8s.io`:
                # https://gateway-api.sigs.k8s.io/reference/spec/#httproute
                HTTPRoute(
                    name="http-route",
                    listener=http_listener,
                    matches=[HTTPRouteMatch(path=HTTPPathMatch(value=self.path_prefix))],
                    filters=[
                        URLRewriteFilter(
                            urlRewrite=URLRewriteSpec(
                                path=PathModifier(
                                    type=PathModifierType.ReplacePrefixMatch,
                                    value=self.url_rewrite,
                                )
                            )
                        )
                    ],
                    backends=[BackendRef(service=self.service_name, port=self.service_port)],
                ),
            ],
        )

    def _configure_app_leader(self, _):
        if self.ingress.is_ready():
            try:
                self.ingress.submit_config(self.self._get_ingress_config())
            except Exception as e:
                raise GenericCharmRuntimeError(f"Failed to submit ingress config: {e}")
        else:
            logger.debug("Ambient ingress relation not ready, skipping config submission.")

    def get_status(self):  # noqa: D102
        # This component depends on LeadershipGateComponent so no need to check for leadership here
        # If ingress config failed, the `_configure_app_leader` method raises an error
        # Otherwise simply return ActiveStatus()
        return ActiveStatus()
