name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  schedule:
    - cron: '0 8 * * TUE'
  # Triggered on push by .github/workflows/release.yaml
  workflow_call:
    outputs:
      artifact-prefix:
        description: build_charm.yaml `artifact-prefix` output
        value: ${{ jobs.build.outputs.artifact-prefix }}
      charm-paths:
        description: paths for all charms in this repo
        value: ${{ jobs.get-charm-paths-channel.outputs.charm-paths }}
      channel:
        description: Charmhub channel the charms are released to
        value: ${{ jobs.get-charm-paths-channel.outputs.charm-channel }}

jobs:
  get-charm-paths-channel:
    name: Get charm paths and charmhub channel
    runs-on: ubuntu-latest
    outputs:
      charm-paths: ${{ steps.get-charm-paths.outputs.charm-paths }}
      charm-channel: ${{ steps.select-channel.outputs.name }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get paths for all charms in this repo
        id: get-charm-paths
        uses: canonical/kubeflow-ci/actions/get-charm-paths@main
      - name: Select charmhub channel
        uses: canonical/charming-actions/channel@2.6.2
        id: select-channel

  lib-check:
    name: Check libraries
    needs:
      - get-charm-paths-channel
    strategy:
      matrix:
        charm: ${{ fromJSON(needs.get-charm-paths-channel.outputs.charm-paths) }}
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/_quality-checks.yaml@main
    secrets: inherit
    with:
        charm-path: ${{ matrix.charm }}

  lint:
    name: Lint Check
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        charm: [feast-integrator]

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: pip install tox

    - name: Lint code
      run: tox -vve ${{ matrix.charm }}-lint

  unit:
    name: Unit Test
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        charm: [feast-integrator]

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: pip install tox

    - name: Run unit tests
      run: tox -vve ${{ matrix.charm }}-unit

  terraform-checks:
    name: Terraform
    needs:
      - get-charm-paths-channel
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/terraform-checks.yaml@main
    strategy:
      matrix:
        charm: ${{ fromJSON(needs.get-charm-paths-channel.outputs.charm-paths) }}
    with:
      charm-path: ${{ matrix.charm }}

  build:
    strategy:
      matrix:
        charm: #FIXME remove hard-coding of charm paths  
          - charms/feast-integrator
          - charms/feast-integrator/tests/integration/configuration-requirer-tester
    name: Build charm | ${{ matrix.charm }}
    needs:
      - get-charm-paths-channel
    uses: canonical/data-platform-workflows/.github/workflows/build_charm.yaml@v31.0.1
    with:
      path-to-charm-directory: ${{ matrix.charm }}
      cache: false #TODO remove when tester charm is added to charmcraftcache
    
  integration:
    name: Integration tests (microk8s)
    needs: build
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        charm: [feast-integrator]

    steps:
      - name: Check out code
        uses: actions/checkout@v4
          
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          channel: 1.32-strict/stable
          juju-channel: 3.6/stable
          microk8s-addons: dns hostpath-storage ingress metallb:10.64.140.43-10.64.140.49


      - name: Download packed charm(s)
        id: download-charms
        timeout-minutes: 5
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ needs.build.outputs.artifact-prefix }}-*
          merge-multiple: true

      - run: |
          tox -vve ${{ matrix.charm }}-integration -- --charm-path=${{ github.workspace }}/charms/${{ matrix.charm }}/${{ matrix.charm }}_ubuntu@24.04-amd64.charm

      # Collect debug logs if failed
      - name: Dump Juju/K8s logs on failure
        uses: canonical/charm-logdump-action@main
        if: failure()
        with:
          app: ${{ matrix.charm }}
          model: testing


  release:
    strategy:
      matrix:
        charm: ${{ fromJSON(needs.get-charm-paths-channel.outputs.charm-paths) }}
    name: Release charm to Charmhub branch | ${{ matrix.charm }}
    if: ${{ github.event_name == 'pull_request' }}
    needs:
      - get-charm-paths-channel
      - build
    uses: canonical/data-platform-workflows/.github/workflows/release_charm.yaml@v30.2.0
    with:
      channel: ${{ needs.get-charm-paths-channel.outputs.charm-channel }}
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
      path-to-charm-directory: ${{ matrix.charm }}
      create-git-tags: false
    secrets:
      charmhub-token: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
